<?php

/**
 * @file
 * Code for the Global functions feature.
 */

include_once 'adb_global_functions.features.inc';

/**
 * Implements hook_preprocess_views_view().
 */
function adb_global_functions_preprocess_views_view(&$variables) {
  switch ($variables['view']->name) {
    case 'views_topics_menu':
    case 'views_countries_menu':
      $variables['theme_hook_suggestions'][] = 'views_view_adb_menu';
      drupal_add_js(drupal_get_path('module', 'adb_global_functions') . '/js/adb_global_functions.js');

      break;
  }
}

/**
 * Implements hook_block_info().
 */
function adb_global_functions_block_info() {
  $blocks['adb_profile_access'] = array(
    'info' => t('Profile access'),
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function adb_global_functions_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'adb_profile_access':
      module_load_include('inc', 'adb_global_functions', 'includes/adb_global_functions.blocks');
      $block['content'] = array(
        '#markup' => adb_global_functions_profile_access_markup(),
        '#attached' => array(
          'js' => array(
            drupal_get_path('module', 'adb_global_functions') . '/js/adb_global_functions.js',
          ),
          'css' => array(
            drupal_get_path('module', 'adb_global_functions') . '/css/adb_global_functions.css',
          ),
        ),
      );

      break;

  }

  return $block;
}
